### ISSUE TITLE
ImageNet subset

### ISSUE THREAD

**Issue by siddeshwar-raghavan** [xialeiliu/Long-Tailed-CIL#1]
I am reproducing the GitHub code and can I know the subset of ImageNet used for the experiments? (I.e.) The specific classes chosen from ImageNet for the experiments would be very helpful.

**Comment by Ethanhuhuhu** [comment]
Hello, we update a new file [https://github.com/xialeiliu/Long-Tailed-CIL/blob/main/subset.py](url) and the subset list can be generated with it.
