### ISSUE TITLE
Imagenet subset data

### ISSUE THREAD

**Issue by Yuki-Hong** [xialeiliu/Long-Tailed-CIL#2]
刘老师您好，关注到您的这份工作，我对imagenet-subset的数据这块怎么切分的比较感兴趣，但是在代码和文章中没有看到相关说明，不知道我是否可以得到一份具体的imagenet-subset训练数据

**Comment by Ethanhuhuhu** [comment]
您好，我们新上传的https://github.com/xialeiliu/Long-Tailed-CIL/blob/main/subset.py文件可以在ImageNet基础上直接生成可用的subset列表

**Comment by Ethanhuhuhu** [comment]
您好，我们新上传的文件[https://github.com/xialeiliu/Long-Tailed-CIL/blob/main/subset.py](url)可以直接生成一个subset的列表
