### ISSUE TITLE
How to get accuracies on paper

### ISSUE THREAD

**Issue by rahulvigneswaran** [xialeiliu/Long-Tailed-CIL#5]
How to get the accuracies provided on the paper from the code?

**Comment by Ethanhuhuhu** [comment]
Please run the code and calculate the average the mean accuracy of all tasks.

**Comment by rahulvigneswaran** [comment]
@Ethanhuhuhu 
Say for example if I want the accuracy for eeil_2stage conventional 5 tasks, then I get the following in `avg_accs_tag.txt`

```
0.737400	0.612200	0.558867	0.502400	0.486680	0.471700
```

Is 0.471700 the accuracy that is shown in the paper or should I average all the 6 values?

**Comment by Ethanhuhuhu** [comment]
You should average all the 6 values.
