### ISSUE TITLE
Reproducing Imagenet-subset 

### ISSUE THREAD

**Issue by rahulvigneswaran** [xialeiliu/Long-Tailed-CIL#6]
- [x] #7

- [x] There are a lot of images in the txt files like below that are actually missing from the dataset. What version of imagenet you downloaded? I have cross-checked with other imagenets, so these are not just missing from my folder. Full list of all missing entities - https://gist.github.com/rahulvigneswaran/b89e1d49613616d5505fc5d0141bd69b

- [x] The code doesn't seem to run for Imagenet out of the box, is my understanding that we need to modify the code in order to run imagenet correct?

**Comment by Ethanhuhuhu** [comment]
The subset_train.txt and subset_test.txt are generated by subset.py.

**Comment by Ethanhuhuhu** [comment]
We use imagenet 2012(ISLVRC12), and you just need to modify the datasets options in training scripts to run for imagenet.

**Comment by rahulvigneswaran** [comment]
> The subset_train.txt and subset_test.txt are generated by subset.py.

Can you clarify this? Because from what I can understand `subset.py` reads  `subset_train.txt` and `subset_test.txt` and puts the images in appropriate folders. 

It does not generate `subset_train.txt` and `subset_test.txt`.

**Comment by rahulvigneswaran** [comment]
> We use imagenet 2012(ISLVRC12), and you just need to modify the datasets options in training scripts to run for imagenet.

Did you download only [Training images (Task 1 & 2)](https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_train.tar). 138GB. MD5: 1d675b47d978889d74fa0da5fadfb00e ?

Or did you download [Training images (Task 3)](https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_train_t3.tar). 728MB. MD5: ccaf1013018ac1037801578038d370da too?

**Comment by Ethanhuhuhu** [comment]
I'll check the code, it seems that we change the code after generating the files. Or you can just use seed 1993 to generate a file for your own datasets. Our imagenet is downloaded by senior students who have graduated and it seems different from the official one. You can also use the split generated by dytox[https://github.com/arthurdouillard/dytox/tree/main/imagenet100_splits](url). The results might be different but the 2stage still has advantages.

**Comment by rahulvigneswaran** [comment]
Sure. Can you check the `subset.py` and post the correct one, so I can generate it on my own?

**Comment by YananGu** [comment]
@rahulvigneswaran  Do you know which dataset to download?  Task 1&2 or 3?

**Comment by rahulvigneswaran** [comment]
@YananGu https://github.com/xialeiliu/Long-Tailed-CIL/issues/6#issuecomment-1747002240 fixes the issue.
