### ISSUE TITLE
Unable to obtain accuracies as mentioned in the paper.

### ISSUE THREAD

**Issue by siddeshwar-raghavan** [xialeiliu/Long-Tailed-CIL#8]
I used the ImageNet dataset, split the same way as mentioned in the repo. Trying to reproduce EEIL and LUCIR results for 10 tasks in the shuffled LT case. 
![Screenshot 2023-10-12 at 4 07 28 PM](https://github.com/xialeiliu/Long-Tailed-CIL/assets/22166857/0b4c7d85-3132-4ab6-a50b-e903b7485f59)

However, the best accuracy I could obtain for LUCIR and LUCIR_2stage were 44.29% and 47.73% respectively. For EEIL and EEIL_2stage the accuracies were 40.82% and 42.49%. (Without grid search)

In the reported accuracies, was gridsearch used? Is there anything that is missing in terms of setting to obtain the mentioned accuracies?

**Comment by Ethanhuhuhu** [comment]
Thanks for your interest, could you please share me the log? The reported accuracies are the average accuracy over all tasks, not the last task. It might be the reason.

**Comment by Ethanhuhuhu** [comment]
The gridsearch is not used.

**Comment by siddeshwar-raghavan** [comment]
I am attaching the Task agnostic accuracies from the logs as follows: The calculated accuracy is average across the 10 tasks.
**LUCIR:**
TAg Acc
	 46.8%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 46.8% 
	 43.2%  69.3%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 56.3% 
	 40.4%  56.7%  84.3%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 60.5% 
	 40.8%  55.7%  70.3%  51.7%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 54.6% 
	 34.6%  47.3%  63.0%  48.3%  54.7%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 49.6% 
	 33.5%  45.7%  60.7%  47.0%  47.3%  46.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 46.7% 
	 31.8%  43.7%  56.7%  47.0%  43.0%  40.7%  62.4%   0.0%   0.0%   0.0% 	Avg.: 46.5% 
	 31.4%  43.3%  54.7%  47.0%  43.7%  39.0%  55.6%  46.0%   0.0%   0.0% 	Avg.: 45.1% 
	 29.2%  40.0%  52.0%  42.0%  36.7%  34.3%  36.8%  39.6%  48.0%   0.0% 	Avg.: 39.8% 
	 29.6%  41.0%  53.0%  43.7%  36.7%  35.7%  42.8%  33.6%  46.0%  50.8% 	Avg.: 41.3% 
	 
**LUCIR_2stage**
TAg Acc
	 53.4%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 53.4% 
	 51.4%  67.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 59.2% 
	 46.6%  63.0%  76.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 61.9% 
	 45.4%  58.3%  67.3%  60.7%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 57.9% 
	 42.2%  52.3%  65.0%  54.3%  52.3%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 53.2% 
	 40.2%  49.7%  64.3%  55.0%  46.7%  46.7%   0.0%   0.0%   0.0%   0.0% 	Avg.: 50.4% 
	 38.2%  48.3%  60.0%  50.7%  45.3%  42.0%  62.4%   0.0%   0.0%   0.0% 	Avg.: 49.6% 
	 36.8%  47.7%  57.7%  48.7%  45.7%  39.7%  56.8%  55.2%   0.0%   0.0% 	Avg.: 48.5% 
	 35.4%  48.0%  56.0%  48.3%  42.3%  38.0%  48.0%  52.8%  46.0%   0.0% 	Avg.: 46.1% 
	 34.7%  45.7%  52.7%  47.7%  41.3%  38.0%  47.6%  43.2%  40.4%  58.0% 	Avg.: 44.9% 

**EEIL:**
TAg Acc
	 44.4%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 44.4% 
	 33.3%  76.3%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 54.8% 
	 33.3%  45.7%  83.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 54.0% 
	 33.7%  50.0%  60.7%  59.3%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 50.9% 
	 27.1%  37.7%  51.3%  40.0%  67.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 44.6% 
	 29.1%  38.7%  53.0%  44.0%  37.3%  51.7%   0.0%   0.0%   0.0%   0.0% 	Avg.: 42.3% 
	 27.3%  39.7%  48.0%  41.0%  33.3%  37.3%  68.8%   0.0%   0.0%   0.0% 	Avg.: 42.2% 
	 27.6%  33.3%  48.7%  40.0%  38.7%  32.7%  43.6%  60.4%   0.0%   0.0% 	Avg.: 40.6% 
	 26.4%  34.0%  44.0%  35.7%  30.3%  30.3%  33.2%  37.6%  54.4%   0.0% 	Avg.: 36.2% 
	 28.0%  37.0%  49.7%  40.0%  37.0%  31.0%  38.4%  28.0%  35.6%  66.0% 	Avg.: 39.1% 

**EEIL_2stage:**
TAg Acc
	 52.2%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 52.2% 
	 40.0%  70.3%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 55.2% 
	 35.5%  50.3%  78.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 54.6% 
	 35.8%  49.0%  56.3%  53.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 48.5% 
	 32.8%  41.3%  61.0%  42.0%  56.3%   0.0%   0.0%   0.0%   0.0%   0.0% 	Avg.: 46.7% 
	 33.8%  44.7%  59.0%  42.3%  40.7%  45.3%   0.0%   0.0%   0.0%   0.0% 	Avg.: 44.3% 
	 31.8%  41.3%  51.3%  45.7%  42.0%  31.7%  60.8%   0.0%   0.0%   0.0% 	Avg.: 43.5% 
	 31.5%  43.3%  51.0%  41.3%  38.7%  31.3%  48.0%  51.6%   0.0%   0.0% 	Avg.: 42.1% 
	 29.7%  42.0%  46.7%  40.0%  38.3%  31.0%  41.2%  39.2%  52.4%   0.0% 	Avg.: 40.1% 
	 28.6%  42.7%  47.7%  41.0%  38.0%  30.3%  45.6%  32.8%  33.6%  61.2% 	Avg.: 40.2%

**Comment by siddeshwar-raghavan** [comment]
Would you be able to provide the log files you had generated for your experiments? This would help understand the issue. Additionally, I used seed as 1993.

**Comment by Ethanhuhuhu** [comment]
The accuracy reported is the average accuracy across all tasks. For example, the average incremental accuracy of LUCIR is 46.8+56.3+60.2+ ... + 41.3 = 48.7 and LUCIR_2stage is 53.4+ 59.2+...+46.1+44.9 = 52.1
