### ISSUE TITLE
Heuristics for Class order

### ISSUE THREAD

**Issue by rahulvigneswaran** [xialeiliu/Long-Tailed-CIL#9]
It looks like the Shuffled-LT scenario won't work for all random class orders. I noticed some heuristics when looking at the class_order provided in the config. Can you tell me what heuristics you followed while creating the class order?

**Comment by Ethanhuhuhu** [comment]
The shuffled lt scenario should work for all random class orders. It's generated in [https://github.com/xialeiliu/Long-Tailed-CIL/blob/7db63177de101071b5354f689ec71e0dbe0416f2/src/datasets/base_dataset.py#L32C8-L32C8](url). The order is generated with seed 1993 which is widely used in class incremental learning. You can generate other orders just make class order empty.
